import React, { useState } from 'react'

export default function SelectedPost({selectedData, open}) {
    const [insight, setInsight] = useState()
    const handleSubmit = (e) =>{
        e.preventDefault()
        console.log('work')
    }

  return (
<form onSubmit={handleSubmit} className={`h-screen p-7 flex-col flex overflow-hidden justify-start transition-all duration-500 ease-in-out gap-2 
  ${open ? ' w-96 opacity-100' : 'w-[0px] opacity-0 -z-10'}`}>        {console.log(selectedData)}
        <p>Selected post:</p>
                <div className='h-4/6 w-full rounded-lg border-2 border-[#74747E]' >
                <div style={{ backgroundImage: 'url(./disaster.png)', backgroundSize: "cover"}} className='w-full    h-4/6 w-36  overflow-hidden border-0 bg-gray-100 rounded-t-lg' src={selectedData.imageUrl}/>
                <div className='p-3 flex flex-col gap-'>
                <p>Generated by AI</p>
                <p className='text-xs '>{selectedData.address}</p>
                </div>
                
                <p className=' px-4 b text-sm rounded-lg '>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                </p>
                </div>


                <textarea required onChange={(e) => setInsight(e.target.value)} placeholder='Compose insight' className='h-2/6 w-full rounded-lg border-2 border-[#74747E] p-5 '>
                    
                </textarea>

                <button  className='flex gap-2 bg-[#221B81] text-white  w-48 items-center p-2 rounded-full'>
                    <Sharing/>
                    Broadcast insight
                </button>


    </form>
  )
}

const Sharing = () =>{
return(<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M13.5 16.5C12.875 16.5 12.3438 16.2812 11.9062 15.8438C11.4688 15.4062 11.25 14.875 11.25 14.25C11.25 14.1625 11.2563 14.0719 11.2688 13.9781C11.2812 13.8844 11.3 13.8 11.325 13.725L6.0375 10.65C5.825 10.8375 5.5875 10.9844 5.325 11.0906C5.0625 11.1969 4.7875 11.25 4.5 11.25C3.875 11.25 3.34375 11.0312 2.90625 10.5938C2.46875 10.1562 2.25 9.625 2.25 9C2.25 8.375 2.46875 7.84375 2.90625 7.40625C3.34375 6.96875 3.875 6.75 4.5 6.75C4.7875 6.75 5.0625 6.80312 5.325 6.90938C5.5875 7.01562 5.825 7.1625 6.0375 7.35L11.325 4.275C11.3 4.2 11.2812 4.11562 11.2688 4.02187C11.2563 3.92812 11.25 3.8375 11.25 3.75C11.25 3.125 11.4688 2.59375 11.9062 2.15625C12.3438 1.71875 12.875 1.5 13.5 1.5C14.125 1.5 14.6562 1.71875 15.0938 2.15625C15.5312 2.59375 15.75 3.125 15.75 3.75C15.75 4.375 15.5312 4.90625 15.0938 5.34375C14.6562 5.78125 14.125 6 13.5 6C13.2125 6 12.9375 5.94688 12.675 5.84062C12.4125 5.73438 12.175 5.5875 11.9625 5.4L6.675 8.475C6.7 8.55 6.71875 8.63437 6.73125 8.72812C6.74375 8.82187 6.75 8.9125 6.75 9C6.75 9.0875 6.74375 9.17813 6.73125 9.27188C6.71875 9.36563 6.7 9.45 6.675 9.525L11.9625 12.6C12.175 12.4125 12.4125 12.2656 12.675 12.1594C12.9375 12.0531 13.2125 12 13.5 12C14.125 12 14.6562 12.2188 15.0938 12.6562C15.5312 13.0938 15.75 13.625 15.75 14.25C15.75 14.875 15.5312 15.4062 15.0938 15.8438C14.6562 16.2812 14.125 16.5 13.5 16.5ZM13.5 4.5C13.7125 4.5 13.8906 4.42813 14.0344 4.28438C14.1781 4.14062 14.25 3.9625 14.25 3.75C14.25 3.5375 14.1781 3.35938 14.0344 3.21563C13.8906 3.07188 13.7125 3 13.5 3C13.2875 3 13.1094 3.07188 12.9656 3.21563C12.8219 3.35938 12.75 3.5375 12.75 3.75C12.75 3.9625 12.8219 4.14062 12.9656 4.28438C13.1094 4.42813 13.2875 4.5 13.5 4.5ZM4.5 9.75C4.7125 9.75 4.89062 9.67813 5.03438 9.53438C5.17813 9.39063 5.25 9.2125 5.25 9C5.25 8.7875 5.17813 8.60938 5.03438 8.46563C4.89062 8.32188 4.7125 8.25 4.5 8.25C4.2875 8.25 4.10938 8.32188 3.96563 8.46563C3.82188 8.60938 3.75 8.7875 3.75 9C3.75 9.2125 3.82188 9.39063 3.96563 9.53438C4.10938 9.67813 4.2875 9.75 4.5 9.75ZM13.5 15C13.7125 15 13.8906 14.9281 14.0344 14.7844C14.1781 14.6406 14.25 14.4625 14.25 14.25C14.25 14.0375 14.1781 13.8594 14.0344 13.7156C13.8906 13.5719 13.7125 13.5 13.5 13.5C13.2875 13.5 13.1094 13.5719 12.9656 13.7156C12.8219 13.8594 12.75 14.0375 12.75 14.25C12.75 14.4625 12.8219 14.6406 12.9656 14.7844C13.1094 14.9281 13.2875 15 13.5 15Z" fill="#F9F9FF"/>
</svg>)}
